### ISSUE TITLE
some sent_id not in sg_anno

### ISSUE THREAD

**Issue by VV0808** [youngfly11/LCMCG-PyTorch#12]
Hi! Thank you for your great work. I have some questions about sg_anno.json.

Each picture has five sentences.That means Each picture has five relations in sg_anno.json.

However, when i simply simply pair each image with their caption, like 1.jpg, 0; 1.jpg 1;1.jpg 2;1.jpg 3;1.jpg 4;

sent_id maybe not in sg_anno.json. there are only three or four relations in sg_anno.json, not five.

Even if there are less than five, are they one-to-one？

for example, there are five  sentences about the picture. but there only three relations in  sg_anno.json.

Do these three relationships correspond to the first three sentences？

**Comment by youngfly11** [comment]
Thanks for your interest. I have to point out that each image is associated with 5 captions and each caption(maybe) has multiple relations. Because for flickr30k dataset, there are several noun phrases in one caption. Not all images have five captions but most cases do.

**Comment by youngfly11** [comment]
[train.txt](https://github.com/youngfly11/LCMCG-PyTorch/files/7811592/train.txt)
[val.txt](https://github.com/youngfly11/LCMCG-PyTorch/files/7811593/val.txt)
[test.txt](https://github.com/youngfly11/LCMCG-PyTorch/files/7811594/test.txt)

**Comment by youngfly11** [comment]
I have uploaded the train/val/test files. You can check it now

**Comment by VV0808** [comment]
Thank you！
