### ISSUE TITLE
Not Baidu please

### ISSUE THREAD

**Issue by bareblackfoot** [youngfly11/LCMCG-PyTorch#4]
It's very hard for me to download the dataset.
My computer says that the baidunetdisk has a virus and i don't wanna download the baidu system :(
Would you upload your dataset on google drive?
Please. Thanks

**Comment by youngfly11** [comment]
You can refer the README Now. Hope this will help you

**Comment by bareblackfoot** [comment]
@youngfly11 Thanks a lot :) 
Where are the skip-thoughts? Is it a component of flickr30k? I couldn't find it though..
