### ISSUE TITLE
Skip-thoughts directory

### ISSUE THREAD

**Issue by bareblackfoot** [youngfly11/LCMCG-PyTorch#5]
I think it is a directory for the word embeddings, but I couldn't find it from your uploaded dataset.
Could you upload the skip-thoughts directory on your google drive?

**Comment by youngfly11** [comment]
Hi, our word embedding is trained from scratch. The vocab.json is just a dict, which contains all words in Flickr30k. You can generate it by yourself.

**Comment by bareblackfoot** [comment]
Is it a JSON file using "node.idx"? 
Does it contain phrases like node.idx file or just a single word?
for example. node.idx has "straddle bike".
Maybe I can generate the file but the generated file can have its variation and affect the performance as i think...

**Comment by youngfly11** [comment]
Okay, I have uploaded this file. You can access it in Google Drive. 

It's not easy for me to access Google! (you maybe do not understand this)
